// Types for Pricing Rules

export interface PricingRule {
  RuleId: number
  RuleDescription: string
  Lenders: string[]
  Fee: number
  Price: number
  CompPercent: number
  Active: boolean
  Disallow: boolean
  RuleIsDeleted: boolean
  // Step 1 fields
  LockPeriod: number
  FeeSet: string
  MICompany: string
  Rate: string
  MarginType: 'percentage' | 'flat'
  CompMin: number
  CompMax: number
  CompFlatFee: number
  FinalPriceMin: number
  FinalPriceMax: number
  HasSecondMortgage: boolean
  IgnoreNonEighthRates: boolean
  IncludeUFMIP: boolean
  MaxCashBack: number
  FinanceUFMIP: boolean
  // Step 2 fields
  LTVMin: number
  LTVMax: number
  FICOMin: number
  FICOMax: number
  LoanAmountMin: number
  LoanAmountMax: number
  PropertyTypes: string[]
  PropertyUsage: string[]
  LoanTypes: string[]
  QuotingChannels: string[]
  LockPeriods: number[]
  BorrowerFilters: string[]
  PointGroups: string[]
  States: string[]
  // Step 3 fields
  ProductFamilies: string[]
  ProductClasses: string[]
  ProductTypes: string[]
  ProductTerms: string[]
  // Step 4 fields
  StartDate: string | null
  EndDate: string | null
  StartTime: string | null
  EndTime: string | null
  // Visibility
  HideInQuoteAdjustments: boolean
}

export type DraftType = 'create' | 'update' | 'delete' | 'restore' | 'toggleActive'

export interface DraftEntry {
  ruleId: number
  type: DraftType
  originalRule?: PricingRule
  updatedRule: PricingRule
  changedFields?: string[]
}

// Sample Lenders
export const LENDERS = [
  'Flagstar Bank',
  'United Wholesale Mortgage',
  'PennyMac',
  'Rocket Mortgage',
  'NewRez',
  'AmeriHome Mortgage',
  'Freedom Mortgage',
  'Mr. Cooper',
  'Caliber Home Loans',
  'Guild Mortgage',
  'loanDepot',
  'Chase Home Lending',
  'Wells Fargo',
  'Bank of America',
  'US Bank',
]

export const PROPERTY_TYPES = ['SFH', 'Townhouse', 'Condo 4-', 'Condo 5+', 'Multi 2', 'Multi 3-4']
export const PROPERTY_USAGE = ['Primary', 'Secondary', 'Investment']
export const LOAN_TYPES = ['Purchase', 'Refinance', 'Cash Out', 'HEL', 'HELOC']
export const QUOTING_CHANNELS = ['Retail', 'Wholesale', 'Correspondent', 'Consumer Direct']
export const LOCK_PERIODS = [15, 30, 45, 60, 75, 90, 120, 180]
export const BORROWER_FILTERS = ['Bankruptcy', 'Foreclosure', 'First Time Buyer', 'Self Employed', 'Non-QM', 'Foreign National']
export const POINT_GROUPS = ['-1 No Fee', '0 Point', '1 Point', '2 Point', '3 Point']
export const STATES = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
export const PRODUCT_FAMILIES = ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Non-QM']
export const PRODUCT_CLASSES = ['Fixed', 'ARM', 'Hybrid']
export const PRODUCT_TYPES = ['Agency', 'Non-Agency', 'Government']
export const PRODUCT_TERMS = ['10 Year', '15 Year', '20 Year', '25 Year', '30 Year', '40 Year']
export const FEE_SETS = ['Standard', 'Low Fee', 'Premium', 'Wholesale']
export const MI_COMPANIES = ['MGIC', 'Radian', 'Essent', 'National MI', 'Arch MI', 'Genworth']

// Generate sample rules
function getRandomLenders(count: number): string[] {
  const shuffled = [...LENDERS].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

function getRandomItems<T>(arr: T[], count: number): T[] {
  const shuffled = [...arr].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

export const generateSampleRules = (): PricingRule[] => {
  const rules: PricingRule[] = [
    // Conventional Rules
    {
      RuleId: 1001,
      RuleDescription: 'Conv 30yr FICO 760+ Purchase',
      Lenders: getRandomLenders(4),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 760,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1002,
      RuleDescription: 'Conv 30yr FICO 720-759 Purchase',
      Lenders: getRandomLenders(5),
      Fee: 250,
      Price: -0.25,
      CompPercent: 2.375,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '7.0',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 759,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1003,
      RuleDescription: 'Conv 30yr FICO 680-719 Purchase',
      Lenders: getRandomLenders(6),
      Fee: 500,
      Price: -0.5,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Essent',
      Rate: '7.125',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 85,
      FICOMin: 680,
      FICOMax: 719,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ', 'CO', 'WA'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1004,
      RuleDescription: 'Conv 30yr FICO 620-679 Purchase',
      Lenders: getRandomLenders(4),
      Fee: 750,
      Price: -1.0,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'National MI',
      Rate: '7.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 3500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 1500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 90,
      FICOMin: 620,
      FICOMax: 679,
      LoanAmountMin: 100000,
      LoanAmountMax: 548250,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // FHA Rules
    {
      RuleId: 1005,
      RuleDescription: 'FHA All Products',
      Lenders: getRandomLenders(8),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'FHA',
      Rate: '6.5',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 3000,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 96.5,
      FICOMin: 580,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES.slice(0, 30),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1006,
      RuleDescription: 'FHA Streamline Refi',
      Lenders: getRandomLenders(6),
      Fee: 0,
      Price: 0.25,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: 'FHA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 500,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 97.75,
      FICOMin: 580,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: STATES.slice(0, 40),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // VA Rules
    {
      RuleId: 1007,
      RuleDescription: 'VA IRRRL Overlay',
      Lenders: getRandomLenders(7),
      Fee: 0,
      Price: 0.375,
      CompPercent: 2.625,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'VA',
      Rate: '6.125',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 5500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES,
      ProductFamilies: ['VA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1008,
      RuleDescription: 'VA Purchase All States',
      Lenders: getRandomLenders(9),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'VA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-', 'Multi 2'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES,
      ProductFamilies: ['VA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Jumbo Rules
    {
      RuleId: 1009,
      RuleDescription: 'Jumbo ARM 5/1 Overlay',
      Lenders: getRandomLenders(3),
      Fee: 1500,
      Price: -0.75,
      CompPercent: 1.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 10000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'TX', 'WA', 'CO'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1010,
      RuleDescription: 'Jumbo Fixed 30yr High FICO',
      Lenders: getRandomLenders(4),
      Fee: 1000,
      Price: -0.5,
      CompPercent: 1.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.25',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 12000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 760,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 2500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Correspondent'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'TX', 'WA', 'CO', 'MA', 'NJ'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Cash Out Refi
    {
      RuleId: 1011,
      RuleDescription: 'Cash Out Refi LTV Cap',
      Lenders: getRandomLenders(5),
      Fee: 500,
      Price: -0.625,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '7.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 75000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Cash Out'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // HELOC
    {
      RuleId: 1012,
      RuleDescription: 'HELOC Primary Only',
      Lenders: getRandomLenders(3),
      Fee: 250,
      Price: 0.0,
      CompPercent: 1.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: '',
      Rate: '8.5',
      MarginType: 'flat',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 500,
      FinalPriceMin: 99,
      FinalPriceMax: 101,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 250000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 85,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 25000,
      LoanAmountMax: 500000,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['HELOC'],
      QuotingChannels: ['Consumer Direct'],
      LockPeriods: [30],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 20),
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['10 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Inactive rules
    {
      RuleId: 1013,
      RuleDescription: 'Conv 15yr High Balance INACTIVE',
      Lenders: getRandomLenders(4),
      Fee: 0,
      Price: 0.25,
      CompPercent: 2.0,
      Active: false,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '6.5',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 1089300,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'MA', 'NJ', 'CT'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1014,
      RuleDescription: 'Investment Property Overlay INACTIVE',
      Lenders: getRandomLenders(3),
      Fee: 1000,
      Price: -1.25,
      CompPercent: 1.75,
      Active: false,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.75',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 1000000,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Investment'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL', 'AZ', 'NV'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Deleted rules
    {
      RuleId: 1015,
      RuleDescription: 'USDA Rural DELETED',
      Lenders: getRandomLenders(2),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: true,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'USDA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 640,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 377600,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 25),
      ProductFamilies: ['USDA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Disallow rules
    {
      RuleId: 1016,
      RuleDescription: 'Disallow Non-QM Below 660 FICO',
      Lenders: getRandomLenders(10),
      Fee: 0,
      Price: 0.0,
      CompPercent: 0,
      Active: true,
      Disallow: true,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: '',
      Rate: '',
      MarginType: 'percentage',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 0,
      FICOMax: 659,
      LoanAmountMin: 0,
      LoanAmountMax: 10000000,
      PropertyTypes: PROPERTY_TYPES,
      PropertyUsage: PROPERTY_USAGE,
      LoanTypes: LOAN_TYPES,
      QuotingChannels: QUOTING_CHANNELS,
      LockPeriods: LOCK_PERIODS,
      BorrowerFilters: [],
      PointGroups: POINT_GROUPS,
      States: STATES,
      ProductFamilies: ['Non-QM'],
      ProductClasses: PRODUCT_CLASSES,
      ProductTypes: PRODUCT_TYPES,
      ProductTerms: PRODUCT_TERMS,
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: true,
    },
    // More varied rules
    {
      RuleId: 1017,
      RuleDescription: 'Conv Refi Rate/Term Only',
      Lenders: getRandomLenders(6),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.375,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Essent',
      Rate: '6.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 40),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1018,
      RuleDescription: 'Second Home Conv 30yr',
      Lenders: getRandomLenders(5),
      Fee: 500,
      Price: -0.375,
      CompPercent: 2.125,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'Arch MI',
      Rate: '7.125',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Secondary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['FL', 'AZ', 'CO', 'CA', 'HI', 'SC', 'NC'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1019,
      RuleDescription: 'Non-QM Bank Statement',
      Lenders: getRandomLenders(4),
      Fee: 2000,
      Price: -1.5,
      CompPercent: 3.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '8.25',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 8000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 50000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 2000000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Investment'],
      LoanTypes: ['Purchase', 'Refinance', 'Cash Out'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: ['Self Employed'],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'FL', 'TX', 'NY', 'AZ', 'NV'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed', 'ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1020,
      RuleDescription: 'Non-QM DSCR Investor',
      Lenders: getRandomLenders(3),
      Fee: 2500,
      Price: -2.0,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '8.5',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 10000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 660,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Investment'],
      LoanTypes: ['Purchase', 'Refinance', 'Cash Out'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'FL', 'TX', 'GA', 'AZ', 'NC', 'TN'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed', 'ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1021,
      RuleDescription: 'Conv ARM 7/1 Primary',
      Lenders: getRandomLenders(5),
      Fee: 0,
      Price: 0.5,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 200000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 30),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['ARM', 'Hybrid'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1022,
      RuleDescription: 'FHA 203k Renovation',
      Lenders: getRandomLenders(4),
      Fee: 750,
      Price: -0.25,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Standard',
      MICompany: 'FHA',
      Rate: '7.0',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 96.5,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [60, 90, 120],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1023,
      RuleDescription: 'High LTV Conv > 90%',
      Lenders: getRandomLenders(4),
      Fee: 500,
      Price: -0.875,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Genworth',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 1000,
      FinanceUFMIP: false,
      LTVMin: 90.01,
      LTVMax: 97,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 548250,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 25),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1024,
      RuleDescription: 'Condo Non-Warrantable',
      Lenders: getRandomLenders(3),
      Fee: 1500,
      Price: -1.25,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.875',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['FL', 'NY', 'CA', 'MA', 'IL', 'WA'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1025,
      RuleDescription: 'Conv 20yr Fixed',
      Lenders: getRandomLenders(5),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.75',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['20 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Another deleted rule
    {
      RuleId: 1026,
      RuleDescription: 'Old ARM 3/1 DELETED',
      Lenders: getRandomLenders(2),
      Fee: 0,
      Price: 0.75,
      CompPercent: 2.0,
      Active: false,
      Disallow: false,
      RuleIsDeleted: true,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '5.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 20),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1027,
      RuleDescription: 'Foreign National Non-QM',
      Lenders: getRandomLenders(2),
      Fee: 2500,
      Price: -2.0,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '9.0',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 8000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 65,
      FICOMin: 0,
      FICOMax: 850,
      LoanAmountMin: 200000,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Investment'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [60, 90],
      BorrowerFilters: ['Foreign National'],
      PointGroups: ['1 Point', '2 Point', '3 Point'],
      States: ['FL', 'CA', 'NY', 'TX'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1028,
      RuleDescription: 'HEL Fixed 15yr',
      Lenders: getRandomLenders(3),
      Fee: 500,
      Price: 0.0,
      CompPercent: 0.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: '',
      Rate: '8.75',
      MarginType: 'flat',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 750,
      FinalPriceMin: 99,
      FinalPriceMax: 101,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 150000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 25000,
      LoanAmountMax: 350000,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['HEL'],
      QuotingChannels: ['Consumer Direct', 'Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 30),
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1029,
      RuleDescription: 'Jumbo Interest Only',
      Lenders: getRandomLenders(2),
      Fee: 2000,
      Price: -1.0,
      CompPercent: 1.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.75',
      MarginType: 'percentage',
      CompMin: 4000,
      CompMax: 15000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 70,
      FICOMin: 740,
      FICOMax: 850,
      LoanAmountMin: 1000000,
      LoanAmountMax: 5000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'WA', 'MA'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1030,
      RuleDescription: 'Texas 50(a)(6) Cash Out',
      Lenders: getRandomLenders(4),
      Fee: 1000,
      Price: -0.75,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 75000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Cash Out'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['TX'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
  ]

  return rules
}

// Helper to create a blank rule for new entries
export const createBlankRule = (tempId: number): PricingRule => ({
  RuleId: tempId,
  RuleDescription: '',
  Lenders: [],
  Fee: 0,
  Price: 0,
  CompPercent: 2.5,
  Active: true,
  Disallow: false,
  RuleIsDeleted: false,
  LockPeriod: 30,
  FeeSet: 'Standard',
  MICompany: '',
  Rate: '',
  MarginType: 'percentage',
  CompMin: 1500,
  CompMax: 5000,
  CompFlatFee: 0,
  FinalPriceMin: 0,
  FinalPriceMax: 0,
  HasSecondMortgage: false,
  IgnoreNonEighthRates: true,
  IncludeUFMIP: false,
  MaxCashBack: 0,
  FinanceUFMIP: false,
  LTVMin: 0,
  LTVMax: 100,
  FICOMin: 0,
  FICOMax: 850,
  LoanAmountMin: 0,
  LoanAmountMax: 10000000,
  PropertyTypes: [],
  PropertyUsage: [],
  LoanTypes: [],
  QuotingChannels: [],
  LockPeriods: [],
  BorrowerFilters: [],
  PointGroups: [],
  States: [],
  ProductFamilies: [],
  ProductClasses: [],
  ProductTypes: [],
  ProductTerms: [],
  StartDate: null,
  EndDate: null,
  StartTime: null,
  EndTime: null,
  HideInQuoteAdjustments: false,
})

// Utility functions for formatting
export const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value)
}

export const formatPrice = (value: number): string => {
  return value.toFixed(3)
}

export const formatPercent = (value: number): string => {
  return `${value.toFixed(3)}%`
}

export const formatLoanAmount = (value: number): string => {
  if (value >= 1000000) {
    return `$${(value / 1000000).toFixed(2)}M`
  }
  return `$${(value / 1000).toFixed(0)}K`
}

// Get changed fields between two rules
export const getChangedFields = (original: PricingRule, updated: PricingRule): string[] => {
  const changes: string[] = []
  const keys = Object.keys(original) as (keyof PricingRule)[]
  
  for (const key of keys) {
    const origVal = original[key]
    const updVal = updated[key]
    
    if (Array.isArray(origVal) && Array.isArray(updVal)) {
      if (JSON.stringify(origVal.sort()) !== JSON.stringify(updVal.sort())) {
        changes.push(key)
      }
    } else if (origVal !== updVal) {
      changes.push(key)
    }
  }
  
  return changes
}
