// Types for Pricing Rules

export interface PricingRule {
  RuleId: number
  RuleDescription: string
  Lenders: string[]
  Fee: number
  Price: number
  CompPercent: number
  Active: boolean
  Disallow: boolean
  RuleIsDeleted: boolean
  // Step 1 fields
  LockPeriod: number
  FeeSet: string
  MICompany: string
  Rate: string
  MarginType: 'percentage' | 'flat'
  CompMin: number
  CompMax: number
  CompFlatFee: number
  FinalPriceMin: number
  FinalPriceMax: number
  HasSecondMortgage: boolean
  IgnoreNonEighthRates: boolean
  IncludeUFMIP: boolean
  MaxCashBack: number
  FinanceUFMIP: boolean
  // Step 2 fields
  LTVMin: number
  LTVMax: number
  FICOMin: number
  FICOMax: number
  LoanAmountMin: number
  LoanAmountMax: number
  PropertyTypes: string[]
  PropertyUsage: string[]
  LoanTypes: string[]
  QuotingChannels: string[]
  LockPeriods: number[]
  BorrowerFilters: string[]
  PointGroups: string[]
  States: string[]
  // Step 3 fields
  ProductFamilies: string[]
  ProductClasses: string[]
  ProductTypes: string[]
  ProductTerms: string[]
  // Step 4 fields
  StartDate: string | null
  EndDate: string | null
  StartTime: string | null
  EndTime: string | null
  // Step 5 fields
  SelectedPrograms?: number[]
  // Visibility
  HideInQuoteAdjustments: boolean
}

export type DraftType = 'create' | 'update' | 'delete' | 'restore' | 'toggleActive'

export interface DraftEntry {
  ruleId: number
  type: DraftType
  originalRule?: PricingRule
  updatedRule: PricingRule
  changedFields?: string[]
}

// Sample Lenders
export const LENDERS = [
  'Flagstar Bank',
  'United Wholesale Mortgage',
  'PennyMac',
  'Rocket Mortgage',
  'NewRez',
  'AmeriHome Mortgage',
  'Freedom Mortgage',
  'Mr. Cooper',
  'Caliber Home Loans',
  'Guild Mortgage',
  'loanDepot',
  'Chase Home Lending',
  'Wells Fargo',
  'Bank of America',
  'US Bank',
]

export const PROPERTY_TYPES = ['SFH', 'Townhouse', 'Condo 4-', 'Condo 5+', 'Multi 2', 'Multi 3-4']
export const PROPERTY_USAGE = ['Primary', 'Secondary', 'Investment']
export const LOAN_TYPES = ['Purchase', 'Refinance', 'Cash Out', 'HEL', 'HELOC']
export const QUOTING_CHANNELS = ['Retail', 'Wholesale', 'Correspondent', 'Consumer Direct']
export const LOCK_PERIODS = [15, 30, 45, 60, 75, 90, 120, 180]
export const BORROWER_FILTERS = ['Bankruptcy', 'Foreclosure', 'First Time Buyer', 'Self Employed', 'Non-QM', 'Foreign National']
export const POINT_GROUPS = ['-1 No Fee', '0 Point', '1 Point', '2 Point', '3 Point']
export const STATES = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
export const PRODUCT_FAMILIES = ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Non-QM']
export const PRODUCT_CLASSES = ['Fixed', 'ARM', 'Hybrid']
export const PRODUCT_TYPES = ['Agency', 'Non-Agency', 'Government']
export const PRODUCT_TERMS = ['10 Year', '15 Year', '20 Year', '25 Year', '30 Year', '40 Year']
export const FEE_SETS = ['Standard', 'Low Fee', 'Premium', 'Wholesale']
export const MI_COMPANIES = ['MGIC', 'Radian', 'Essent', 'National MI', 'Arch MI', 'Genworth']

// Generate sample rules with deterministic data (no Math.random for SSR compatibility)
// Use pure functions with explicit seed parameter for hydration safety
function getLendersForRule(ruleIndex: number, count: number): string[] {
  const start = (ruleIndex * 3) % LENDERS.length
  const result: string[] = []
  for (let i = 0; i < count; i++) {
    result.push(LENDERS[(start + i) % LENDERS.length])
  }
  return result
}

// Pre-defined static lender lists for each rule to ensure SSR/client match
const RULE_LENDERS: Record<number, string[]> = {
  1001: ['Rocket Mortgage', 'United Wholesale Mortgage', 'PennyMac', 'loanDepot'],
  1002: ['Wells Fargo', 'Chase Home Lending', 'Bank of America', 'Caliber Home Loans', 'Freedom Mortgage'],
  1003: ['Mr. Cooper', 'Flagstar Bank', 'NewRez', 'Guild Mortgage', 'AmeriHome Mortgage', 'US Bank'],
  1004: ['Rocket Mortgage', 'PennyMac', 'loanDepot', 'Wells Fargo'],
  1005: ['Chase Home Lending', 'Bank of America', 'United Wholesale Mortgage'],
  1006: ['Caliber Home Loans', 'Freedom Mortgage', 'Mr. Cooper', 'Flagstar Bank', 'NewRez'],
  1007: ['Guild Mortgage', 'AmeriHome Mortgage', 'US Bank', 'Rocket Mortgage'],
  1008: ['PennyMac', 'loanDepot', 'Wells Fargo', 'Chase Home Lending', 'Bank of America'],
  1009: ['United Wholesale Mortgage', 'Caliber Home Loans', 'Freedom Mortgage'],
  1010: ['Mr. Cooper', 'Flagstar Bank', 'NewRez', 'Guild Mortgage'],
  1011: ['AmeriHome Mortgage', 'US Bank', 'Rocket Mortgage', 'PennyMac', 'loanDepot'],
  1012: ['Wells Fargo', 'Chase Home Lending', 'Bank of America'],
  1013: ['United Wholesale Mortgage', 'Caliber Home Loans', 'Freedom Mortgage', 'Mr. Cooper'],
  1014: ['Flagstar Bank', 'NewRez', 'Guild Mortgage', 'AmeriHome Mortgage', 'US Bank'],
  1015: ['Rocket Mortgage', 'PennyMac', 'loanDepot'],
  1016: ['Wells Fargo', 'Chase Home Lending', 'Bank of America', 'United Wholesale Mortgage'],
  1017: ['Caliber Home Loans', 'Freedom Mortgage', 'Mr. Cooper', 'Flagstar Bank', 'NewRez', 'Guild Mortgage'],
  1018: ['AmeriHome Mortgage', 'US Bank', 'Rocket Mortgage', 'PennyMac'],
  1019: ['loanDepot', 'Wells Fargo', 'Chase Home Lending'],
  1020: ['Bank of America', 'United Wholesale Mortgage', 'Caliber Home Loans', 'Freedom Mortgage', 'Mr. Cooper'],
  1021: ['Flagstar Bank', 'NewRez', 'Guild Mortgage', 'AmeriHome Mortgage'],
  1022: ['US Bank', 'Rocket Mortgage', 'PennyMac', 'loanDepot', 'Wells Fargo'],
  1023: ['Chase Home Lending', 'Bank of America', 'United Wholesale Mortgage'],
  1024: ['Caliber Home Loans', 'Freedom Mortgage', 'Mr. Cooper', 'Flagstar Bank'],
  1025: ['NewRez', 'Guild Mortgage', 'AmeriHome Mortgage', 'US Bank', 'Rocket Mortgage'],
  1026: ['PennyMac', 'loanDepot', 'Wells Fargo'],
  1027: ['Chase Home Lending', 'Bank of America', 'United Wholesale Mortgage', 'Caliber Home Loans'],
  1028: ['Freedom Mortgage', 'Mr. Cooper', 'Flagstar Bank', 'NewRez', 'Guild Mortgage'],
  1029: ['AmeriHome Mortgage', 'US Bank', 'Rocket Mortgage', 'PennyMac'],
  1030: ['loanDepot', 'Wells Fargo', 'Chase Home Lending', 'Bank of America', 'United Wholesale Mortgage', 'Caliber Home Loans'],
  1031: ['Freedom Mortgage', 'Mr. Cooper', 'Flagstar Bank'],
  1032: ['NewRez', 'Guild Mortgage', 'AmeriHome Mortgage', 'US Bank'],
  1033: ['Rocket Mortgage', 'PennyMac', 'loanDepot', 'Wells Fargo', 'Chase Home Lending'],
  1034: ['Bank of America', 'United Wholesale Mortgage', 'Caliber Home Loans'],
}

function getLenders(ruleId: number): string[] {
  return RULE_LENDERS[ruleId] || getLendersForRule(ruleId, 4)
}

// Deterministic item selection for arrays (used for States, etc.)
function getRandomItems<T>(arr: T[], count: number, seed: number = 0): T[] {
  const start = seed % arr.length
  const result: T[] = []
  for (let i = 0; i < Math.min(count, arr.length); i++) {
    result.push(arr[(start + i) % arr.length])
  }
  return result
}

export const generateSampleRules = (): PricingRule[] => {
  const rules: PricingRule[] = [
    // Conventional Rules
    {
      RuleId: 1001,
      RuleDescription: 'Conv 30yr FICO 760+ Purchase',
      Lenders: getLenders(1001),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 760,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1002,
      RuleDescription: 'Conv 30yr FICO 720-759 Purchase',
      Lenders: getLenders(1002),
      Fee: 250,
      Price: -0.25,
      CompPercent: 2.375,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '7.0',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 759,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1003,
      RuleDescription: 'Conv 30yr FICO 680-719 Purchase',
      Lenders: getLenders(1003),
      Fee: 500,
      Price: -0.5,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Essent',
      Rate: '7.125',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 85,
      FICOMin: 680,
      FICOMax: 719,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL', 'NY', 'AZ', 'CO', 'WA'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1004,
      RuleDescription: 'Conv 30yr FICO 620-679 Purchase',
      Lenders: getLenders(1004),
      Fee: 750,
      Price: -1.0,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'National MI',
      Rate: '7.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 3500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 1500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 90,
      FICOMin: 620,
      FICOMax: 679,
      LoanAmountMin: 100000,
      LoanAmountMax: 548250,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // FHA Rules
    {
      RuleId: 1005,
      RuleDescription: 'Conv 15yr FICO 760+ Purchase',
      Lenders: getLenders(1005),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'FHA',
      Rate: '6.5',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 3000,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 96.5,
      FICOMin: 580,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES.slice(0, 30),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1006,
      RuleDescription: 'Conv 15yr FICO 720-759 Purchase',
      Lenders: getLenders(1006),
      Fee: 0,
      Price: 0.25,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: 'FHA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 500,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 97.75,
      FICOMin: 580,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: STATES.slice(0, 40),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // VA Rules
    {
      RuleId: 1007,
      RuleDescription: 'FHA 30yr FICO 680+ Purchase',
      Lenders: getLenders(1007),
      Fee: 0,
      Price: 0.375,
      CompPercent: 2.625,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'VA',
      Rate: '6.125',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 5500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES,
      ProductFamilies: ['VA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1008,
      RuleDescription: 'FHA 30yr FICO 620-679 Purchase',
      Lenders: getLenders(1008),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'VA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-', 'Multi 2'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale', 'Correspondent'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: STATES,
      ProductFamilies: ['VA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Jumbo Rules
    {
      RuleId: 1009,
      RuleDescription: 'VA 30yr FICO 680+ Purchase',
      Lenders: getLenders(1009),
      Fee: 1500,
      Price: -0.75,
      CompPercent: 1.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 10000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'TX', 'WA', 'CO'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1010,
      RuleDescription: 'VA 30yr FICO 620-679 Purchase',
      Lenders: getLenders(1010),
      Fee: 1000,
      Price: -0.5,
      CompPercent: 1.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.25',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 12000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 760,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 2500000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Correspondent'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'TX', 'WA', 'CO', 'MA', 'NJ'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Cash Out Refi
    {
      RuleId: 1011,
      RuleDescription: 'Jumbo 30yr FICO 760+ Purchase',
      Lenders: getLenders(1011),
      Fee: 500,
      Price: -0.625,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '7.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 75000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Cash Out'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // HELOC
    {
      RuleId: 1012,
      RuleDescription: 'Conv 30yr FICO 760+ Refinance',
      Lenders: getLenders(1012),
      Fee: 250,
      Price: 0.0,
      CompPercent: 1.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: '',
      Rate: '8.5',
      MarginType: 'flat',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 500,
      FinalPriceMin: 99,
      FinalPriceMax: 101,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 250000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 85,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 25000,
      LoanAmountMax: 500000,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['HELOC'],
      QuotingChannels: ['Consumer Direct'],
      LockPeriods: [30],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 20),
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['10 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Inactive rules
    {
      RuleId: 1013,
      RuleDescription: 'Conv 30yr FICO 720-759 Refinance',
      Lenders: getLenders(1013),
      Fee: 0,
      Price: 0.25,
      CompPercent: 2.0,
      Active: false,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '6.5',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 726201,
      LoanAmountMax: 1089300,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'MA', 'NJ', 'CT'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1014,
      RuleDescription: 'FHA 30yr FICO 680+ Refinance',
      Lenders: getLenders(1014),
      Fee: 1000,
      Price: -1.25,
      CompPercent: 1.75,
      Active: false,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.75',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 1000000,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Investment'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['1 Point', '2 Point'],
      States: ['CA', 'TX', 'FL', 'AZ', 'NV'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Deleted rules
    {
      RuleId: 1015,
      RuleDescription: 'VA 30yr FICO 680+ Refinance IRRRL',
      Lenders: getLenders(1015),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: true,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'USDA',
      Rate: '6.25',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 640,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 377600,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [45, 60],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 25),
      ProductFamilies: ['USDA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Disallow rules
    {
      RuleId: 1016,
      RuleDescription: 'Conv 30yr FICO 760+ Cash-Out',
      Lenders: getLenders(1016),
      Fee: 0,
      Price: 0.0,
      CompPercent: 0,
      Active: true,
      Disallow: true,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: '',
      Rate: '',
      MarginType: 'percentage',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 100,
      FICOMin: 0,
      FICOMax: 659,
      LoanAmountMin: 0,
      LoanAmountMax: 10000000,
      PropertyTypes: PROPERTY_TYPES,
      PropertyUsage: PROPERTY_USAGE,
      LoanTypes: LOAN_TYPES,
      QuotingChannels: QUOTING_CHANNELS,
      LockPeriods: LOCK_PERIODS,
      BorrowerFilters: [],
      PointGroups: POINT_GROUPS,
      States: STATES,
      ProductFamilies: ['Non-QM'],
      ProductClasses: PRODUCT_CLASSES,
      ProductTypes: PRODUCT_TYPES,
      ProductTerms: PRODUCT_TERMS,
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: true,
    },
    // More varied rules
    {
      RuleId: 1017,
      RuleDescription: 'ARM 5/1 FICO 720+ Purchase',
      Lenders: getLenders(1017),
      Fee: 0,
      Price: 0.0,
      CompPercent: 2.375,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Essent',
      Rate: '6.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 40),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1018,
      RuleDescription: 'ARM 7/1 FICO 720+ Purchase',
      Lenders: getLenders(1018),
      Fee: 500,
      Price: -0.375,
      CompPercent: 2.125,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'Arch MI',
      Rate: '7.125',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Secondary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['FL', 'AZ', 'CO', 'CA', 'HI', 'SC', 'NC'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1019,
      RuleDescription: 'USDA 30yr FICO 640+ Purchase',
      Lenders: getLenders(1019),
      Fee: 2000,
      Price: -1.5,
      CompPercent: 3.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '8.25',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 8000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 50000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 2000000,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Investment'],
      LoanTypes: ['Purchase', 'Refinance', 'Cash Out'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: ['Self Employed'],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'FL', 'TX', 'NY', 'AZ', 'NV'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed', 'ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1020,
      RuleDescription: 'Non-QM Bank Statement 24mo',
      Lenders: getLenders(1020),
      Fee: 2500,
      Price: -2.0,
      CompPercent: 2.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '8.5',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 10000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 660,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Investment'],
      LoanTypes: ['Purchase', 'Refinance', 'Cash Out'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [45, 60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['CA', 'FL', 'TX', 'GA', 'AZ', 'NC', 'TN'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed', 'ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1021,
      RuleDescription: 'Non-QM DSCR Investment',
      Lenders: getLenders(1021),
      Fee: 0,
      Price: 0.5,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.375',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 200000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 30),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['ARM', 'Hybrid'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1022,
      RuleDescription: 'Home Equity Line of Credit (HELOC)',
      Lenders: getLenders(1022),
      Fee: 750,
      Price: -0.25,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Standard',
      MICompany: 'FHA',
      Rate: '7.0',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: true,
      MaxCashBack: 0,
      FinanceUFMIP: true,
      LTVMin: 0,
      LTVMax: 96.5,
      FICOMin: 620,
      FICOMax: 850,
      LoanAmountMin: 50000,
      LoanAmountMax: 472030,
      PropertyTypes: ['SFH', 'Multi 2', 'Multi 3-4'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [60, 90, 120],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['FHA'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Government'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1023,
      RuleDescription: 'Home Equity Loan Second Lien',
      Lenders: getLenders(1023),
      Fee: 500,
      Price: -0.875,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Genworth',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 1000,
      FinanceUFMIP: false,
      LTVMin: 90.01,
      LTVMax: 97,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 548250,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: ['First Time Buyer'],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 25),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1024,
      RuleDescription: 'Reverse Mortgage HECM',
      Lenders: getLenders(1024),
      Fee: 1500,
      Price: -1.25,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.875',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 6000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 75,
      FICOMin: 720,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 1500000,
      PropertyTypes: ['Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['FL', 'NY', 'CA', 'MA', 'IL', 'WA'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1025,
      RuleDescription: 'Construction to Permanent Loan',
      Lenders: getLenders(1025),
      Fee: 0,
      Price: 0.125,
      CompPercent: 2.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '6.75',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4500,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 100000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse', 'Condo 4-'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase', 'Refinance'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: getRandomItems(STATES, 35),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['20 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    // Another deleted rule
    {
      RuleId: 1026,
      RuleDescription: 'Conv 30yr High Balance FICO 720+',
      Lenders: getLenders(1026),
      Fee: 0,
      Price: 0.75,
      CompPercent: 2.0,
      Active: false,
      Disallow: false,
      RuleIsDeleted: true,
      LockPeriod: 30,
      FeeSet: 'Standard',
      MICompany: 'Radian',
      Rate: '5.875',
      MarginType: 'percentage',
      CompMin: 1500,
      CompMax: 4000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: false,
      IncludeUFMIP: false,
      MaxCashBack: 2500,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 150000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 20),
      ProductFamilies: ['Conventional'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1027,
      RuleDescription: 'Conv 30yr 2-4 Unit Investment',
      Lenders: getLenders(1027),
      Fee: 2500,
      Price: -2.0,
      CompPercent: 2.5,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '9.0',
      MarginType: 'percentage',
      CompMin: 3000,
      CompMax: 8000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 65,
      FICOMin: 0,
      FICOMax: 850,
      LoanAmountMin: 200000,
      LoanAmountMax: 3000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Investment'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Wholesale'],
      LockPeriods: [60, 90],
      BorrowerFilters: ['Foreign National'],
      PointGroups: ['1 Point', '2 Point', '3 Point'],
      States: ['FL', 'CA', 'NY', 'TX'],
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1028,
      RuleDescription: 'FHA 203k Rehab Loan',
      Lenders: getLenders(1028),
      Fee: 500,
      Price: 0.0,
      CompPercent: 0.75,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 30,
      FeeSet: 'Low Fee',
      MICompany: '',
      Rate: '8.75',
      MarginType: 'flat',
      CompMin: 0,
      CompMax: 0,
      CompFlatFee: 750,
      FinalPriceMin: 99,
      FinalPriceMax: 101,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 150000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 700,
      FICOMax: 850,
      LoanAmountMin: 25000,
      LoanAmountMax: 350000,
      PropertyTypes: ['SFH', 'Townhouse'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['HEL'],
      QuotingChannels: ['Consumer Direct', 'Retail'],
      LockPeriods: [30, 45],
      BorrowerFilters: [],
      PointGroups: ['0 Point'],
      States: getRandomItems(STATES, 30),
      ProductFamilies: ['Non-QM'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1029,
      RuleDescription: 'Renovation Conv HomeStyle',
      Lenders: getLenders(1029),
      Fee: 2000,
      Price: -1.0,
      CompPercent: 1.25,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 60,
      FeeSet: 'Premium',
      MICompany: '',
      Rate: '7.75',
      MarginType: 'percentage',
      CompMin: 4000,
      CompMax: 15000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: false,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 0,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 70,
      FICOMin: 740,
      FICOMax: 850,
      LoanAmountMin: 1000000,
      LoanAmountMax: 5000000,
      PropertyTypes: ['SFH', 'Condo 5+'],
      PropertyUsage: ['Primary', 'Secondary'],
      LoanTypes: ['Purchase'],
      QuotingChannels: ['Retail'],
      LockPeriods: [60, 90],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point'],
      States: ['CA', 'NY', 'FL', 'WA', 'MA'],
      ProductFamilies: ['Jumbo'],
      ProductClasses: ['ARM'],
      ProductTypes: ['Non-Agency'],
      ProductTerms: ['30 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
    {
      RuleId: 1030,
      RuleDescription: 'Conv 30yr Manufactured Home',
      Lenders: getLenders(1030),
      Fee: 1000,
      Price: -0.75,
      CompPercent: 2.0,
      Active: true,
      Disallow: false,
      RuleIsDeleted: false,
      LockPeriod: 45,
      FeeSet: 'Standard',
      MICompany: 'MGIC',
      Rate: '7.5',
      MarginType: 'percentage',
      CompMin: 2000,
      CompMax: 5000,
      CompFlatFee: 0,
      FinalPriceMin: 0,
      FinalPriceMax: 0,
      HasSecondMortgage: true,
      IgnoreNonEighthRates: true,
      IncludeUFMIP: false,
      MaxCashBack: 100000,
      FinanceUFMIP: false,
      LTVMin: 0,
      LTVMax: 80,
      FICOMin: 680,
      FICOMax: 850,
      LoanAmountMin: 75000,
      LoanAmountMax: 726200,
      PropertyTypes: ['SFH'],
      PropertyUsage: ['Primary'],
      LoanTypes: ['Cash Out'],
      QuotingChannels: ['Retail', 'Wholesale'],
      LockPeriods: [45, 60],
      BorrowerFilters: [],
      PointGroups: ['0 Point', '1 Point', '2 Point'],
      States: ['TX'],
      ProductFamilies: ['Conventional'],
      ProductClasses: ['Fixed'],
      ProductTypes: ['Agency'],
      ProductTerms: ['30 Year', '15 Year'],
      StartDate: null,
      EndDate: null,
      StartTime: null,
      EndTime: null,
      HideInQuoteAdjustments: false,
    },
  ]

  return rules
}

// Helper to create a blank rule for new entries
export const createBlankRule = (tempId: number): PricingRule => ({
  RuleId: tempId,
  RuleDescription: '',
  Lenders: [],
  Fee: 0,
  Price: 0,
  CompPercent: 2.5,
  Active: true,
  Disallow: false,
  RuleIsDeleted: false,
  LockPeriod: 30,
  FeeSet: 'Standard',
  MICompany: '',
  Rate: '',
  MarginType: 'percentage',
  CompMin: 1500,
  CompMax: 5000,
  CompFlatFee: 0,
  FinalPriceMin: 0,
  FinalPriceMax: 0,
  HasSecondMortgage: false,
  IgnoreNonEighthRates: true,
  IncludeUFMIP: false,
  MaxCashBack: 0,
  FinanceUFMIP: false,
  LTVMin: 0,
  LTVMax: 100,
  FICOMin: 0,
  FICOMax: 850,
  LoanAmountMin: 0,
  LoanAmountMax: 10000000,
  PropertyTypes: [],
  PropertyUsage: [],
  LoanTypes: [],
  QuotingChannels: [],
  LockPeriods: [],
  BorrowerFilters: [],
  PointGroups: [],
  States: [],
  ProductFamilies: [],
  ProductClasses: [],
  ProductTypes: [],
  ProductTerms: [],
  StartDate: null,
  EndDate: null,
  StartTime: null,
  EndTime: null,
  HideInQuoteAdjustments: false,
})

// Utility functions for formatting
export const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value)
}

export const formatPrice = (value: number): string => {
  return value.toFixed(3)
}

export const formatPercent = (value: number): string => {
  return `${value.toFixed(3)}%`
}

export const formatLoanAmount = (value: number): string => {
  if (value >= 1000000) {
    return `$${(value / 1000000).toFixed(2)}M`
  }
  return `$${(value / 1000).toFixed(0)}K`
}

// Get changed fields between two rules
export const getChangedFields = (original: PricingRule, updated: PricingRule): string[] => {
  const changes: string[] = []
  const keys = Object.keys(original) as (keyof PricingRule)[]
  
  for (const key of keys) {
    const origVal = original[key]
    const updVal = updated[key]
    
    if (Array.isArray(origVal) && Array.isArray(updVal)) {
      if (JSON.stringify(origVal.sort()) !== JSON.stringify(updVal.sort())) {
        changes.push(key)
      }
    } else if (origVal !== updVal) {
      changes.push(key)
    }
  }
  
  return changes
}
